### ISSUE TITLE
Add EULA Consent

### ISSUE THREAD

**Issue by felixklauke** [felixklauke/paper-docker#33]
The user should express their consent via an environment flag at runtime. Consent should NOT be hard coded.

**Comment by Fjiordor** [comment]
Bumping this. I have not been able to consent to the eula and it is unclear to me where to place the eula.txt (with the agreement) in the mounted volumes.

**Comment by fisherthewol** [comment]
Currently in the dockerfile, there is the line:
[`ENV JAVA_ARGS="-server -Dcom.mojang.eula.agree=true"`](https://github.com/FelixKlauke/paperspigot-docker/blob/dev/Dockerfile#L66)

As far as I understand it, making that line
`ENV JAVA_ARGS="-server -Dcom.mojang.eula.agree=false"` would default to _not_ hardcoding consent, and a user could consent using
`--env JAVA_ARGS="-server -Dcom.mojang.eula.agree=true"` at runtime.
However that might not be the best answer.
